apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bartender

resources:
  - namespace.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - redis.yaml
  - worker.yaml
  - observability/prometheus.yaml
  - observability/grafana.yaml
  - load/traffic.yaml
